config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  
  resources :users do
    member do
      get :following, :followers
    end
  end
  match '/signup', to: 'users#new',         via: 'get' 

  resources :sessions, 		only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new',      via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :microposts,	only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]
  
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 140 }

	def self.from_users_followed_by(user)
		followed_user_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
		where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
			followed_user_ids: followed_user_ids, user_id: user)
	end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates :follower, presence: true
	validates :followed, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :microposts, dependent: :destroy
	has_many :relationships, foreign_key: "follower_id", dependent: :destroy
	has_many :followed_users, through: :relationships, source: :followed
	has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
	has_many :followers, through: :reverse_relationships, source: :follower

	before_create :create_remember_token
	before_save { email.downcase! }

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	def feed
		Micropost.from_users_followed_by(self)
	end

	def following?(other_user)
		self.relationships.find_by(followed_id: other_user.id)
	end

	def follow!(other_user)
		self.relationships.create!(followed_id: other_user.id)
	end

	def unfollow!(other_user)
		self.relationships.find_by(followed_id: other_user.id).destroy
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :signed_in_user, 	only: [:create, :destroy]
	before_action :correct_user,		only: :destroy

	def index
	end

	def create
		@micropost = current_user.microposts.build(micropost_params)
		if @micropost.save
			flash[:success] = "投稿しました。"
			redirect_to root_url
		else
			@feed_items = current_user.feed.paginate(page: params[:page])
			flash.now[:error] = @micropost.errors.full_messages.join('　')
			render 'static_pages/home'
		end
	end

	def destroy
		@micropost.destroy
		redirect_to root_url
	end


	private

		def micropost_params
			params.require(:micropost).permit(:content)
		end

		def correct_user
			@micropost = current_user.microposts.find_by(id: params[:id])
			redirect_to root_url if @micropost.nil?
		end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :signed_in_user

	def create
		@user = User.find(params[:relationship][:followed_id])
		current_user.follow!(@user)
		respond_to do |format|
			format.html { redirect_to @user }
			format.js
		end
	end

	def destroy
		@user = Relationship.find(params[:id]).followed
		current_user.unfollow!(@user)
		respond_to do |format|
			format.html { redirect_to @user }
			format.js
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:email].downcase)
		if user && user.authenticate(params[:password])
			sign_in user
			redirect_back_or root_url
		else
			flash.now[:error] = 'エラーメッセージかパスワードが間違っています'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
   if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user,  only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,    only: [:edit, :update]
  before_action :admin_user,      only: :destroy
  before_action :already_singed_in_user, only: [:new, :create]


  def index
    @users = User.paginate(page: params[:page])
  end

	def show
		@user = User.find(params[:id])
	 @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		flash[:success] = "MPosterへようこそ。アカウントを登録しました。"
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを更新しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    if current_user?(user)
      flash[:error] = "ユーザが自分自身のため削除できません。"
    else
      user.destroy
      flash[:success] = "ユーザを削除しました。"
    end
    redirect_to users_url

  end

  def following
    @title = "フォロー"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end


  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

    def already_singed_in_user
      if signed_in?
        @user = current_user
        redirect_to @user
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# ページごとの完全なタイトルを返す
	def full_title(page_title)
		base_title = "MPoster"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "サインインをして下さい。" unless signed_in?
    end
  end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		# current_userが初めて呼び出される場合はDBアクセスするが、
		# 以後の呼び出しではDBにアクセスせずに@current_userを返す
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# 与えられたユーザーのGravatar(http://gravatar.com/)を返す
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		MPoster by <a href="http://ruby-rails.hatenadiary.com/">Shojiro Yanagisawa</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "このサイトについて", about_path %></li>
			<li><%= link_to "お問い合わせ",			 contact_path %></li>
		</ul>
	</nav>		
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<span class="logo">
				<a href="/"><span class="mlogo">M</span>Poster</a>
			</span>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "ホーム",		root_path %></li>
					<li><%= link_to "ヘルプ",  	help_path %></li>
					<% if signed_in? %>
						<li><%= link_to "ユーザ一覧", users_path %></li>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								アカウント <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "私の投稿", current_user %></li>
								<li><%= link_to "設定", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li>
									<%= link_to "ログアウト", signout_path, method: "delete" %>
								</li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "ログイン", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div><!--/#container-->
	</div><!--/#navbar-inner-->
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.google.code.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
	<title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body class='<%= "#{controller.controller_name}-#{controller.action_name}" %>'>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li>
	<span class="content"><%= micropost.content %></span>
	<span class="timestamp">
		投稿日 <%= time_ago_in_words(micropost.created_at) %>前
	</span>
	<% if current_user?(micropost.user) %>
		<%= link_to "削除する", micropost, method: :delete, data: { confirm: "削除してもいいですか？" }, title: micropost.content %> 
	<% end %>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			<%= object.errors.count %>件エラーがあります。
			<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li> * <%= msg %></li>
			<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"><%= feed_item.content %></span>
	<span class="timestamp">
		投稿日 <%= time_ago_in_words(feed_item.created_at) %>前
	</span>
	<% if current_user?(feed_item.user) %>
		<%= link_to "削除する", feed_item, method: :delete, data: { confirm: "削除してもいいですか？" }, title: feed_item.content %> 
	<% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<div class="field">
		<%= f.text_area :content, 
		placeholder: "140文字以内のミニポストメッセージを記入して下さい..." %>
	</div>
	<%= f.submit '投稿する', class: "btn btn-large btn-success" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		フォロー
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		フォロワー
	</a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, size: 52 %>
</a>
<h1>
	<%= current_user.name %>
</h1>
<span>
	<%= link_to "プロフィールを表示", current_user %>
</span>
<span>
	<%= current_user.microposts.count %>ミニポスト
</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'このサイトについて') %>
<h1>このサイトについて</h1>
<p>
	<a href="http://rubyonrails.org/">Ruby on Rails</a>のチュートリアルの<a href="http://railstutorial.org/">Ruby on Rails チュートリアル</a>をベースとして<a href="http://ruby-rails.hatenadiary.com/">Shojiro Yanagisawa</a>が作成しました。
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'お問い合わせ') %>
<h1>お問い合わせ</h1>
<p>
	名前：Shojiro Yanagisawa <br />
  メールアドレス：<a href="mailto:nipe0324@gmail.com">nipe0324@gmail.com</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'ヘルプ') %>
<h1>ヘルプ</h1>
<h3>Twitter同様にツイート、フォローなどの下記の機能があります</h3>
<p>
	<ul>
		<li>認証機能　　...ユーザ登録、ユーザログインができます。</li>
		<li>MPost機能　...Tweetのように140文字以内のMiniPostができます。</li>
		<li>フォロー機能...他ユーザをフォローできます。フォローすると、自分のフィードに他ユーザのMPostが表示されます。</li>
	</ul>
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<div class="row">
		<aside class="span4" style="padding-left:20px;">
			<section>
				<%= render 'shared/user_info' %>
			</section>
			<section>
				<%= render 'shared/stats' %>
			</section>
			<section>
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
		<div class="span8">
			<h3>フィード一覧</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>

<% else %>
	<div class="row home">

		<div class="front-bg">
			<%= image_tag "IMG_0285_30per.JPG", alt: "MPoster home page", class: "front-image" %>
		</div>
		
		<div class="span7">
			<div class="front-welcome">
				<h1>MPosterへようこそ</h1>
				<p>
					Twitterのクローンサイトです。<br />
					Twitter同様にツイート、フォローなどの機能があります。<br />
					より詳細な機能については、<%= link_to "ヘルプ", help_path %>をご覧下さい。
				</p>
			</div>
		</div>

		<session class="span4">
			<div class="front-login">
				<%= form_tag sessions_path do %>
					<%= label_tag :email, "メールアドレス", class: "visuallyhidden" %>
					<%= text_field_tag :email, "", placeholder: "ユーザ名、またはメールアドレス" %>
					<table><tbody><tr>
						<td class="flex-table-primary">
							<%= label_tag :password, "パスワード", class: "visuallyhidden" %>
							<%= password_field_tag :password, "", placeholder: "パスワード" %>
						</td>
						<td class="flex-table-secondary">
							<%= submit_tag "ログイン", class: "btn btn-login" %>
						</td>
					</tr></tbody></table>
				<% end %>
			</div>
		</session>

		<session class="span4">
			<div class="front-signup">
				<h2>MPoster始めませんか？</h2>

		    <%= form_for User.new do |f| %>
					<%= f.label :name, "名前", class: "visuallyhidden" %>
					<%= f.text_field :name, placeholder: "名前" %>
					<%= f.label :email, "メールアドレス", class: "visuallyhidden" %>
					<%= f.text_field :email, placeholder: "メールアドレス" %>
					<%= f.label :password, "パスワード", class: "visuallyhidden" %>
					<%= f.password_field :password, placeholder: "パスワード" %>
					<%= f.label :password_confirmation, "確認用パスワード", class: "visuallyhidden" %>
					<%= f.password_field :password_confirmation, placeholder: "確認用パスワード" %>
					<%= link_to "MPosterへ登録する", signup_path, class: "btn btn-warning" %>
					<span class="test"></span>
  		  <% end %>

			</div>
		</session>

	</div>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name, "名前" %>
<%= f.text_field :name %>

<%= f.label :email, "メールアドレス" %>
<%= f.text_field :email %>

<%= f.label :password, "パスワード" %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "確認用パスワード" %>
<%= f.password_field :password_confirmation %>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
	<div><%= f.hidden_field :followed_id %></div>
	<%= f.submit "フォロー", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
	<% if current_user.following?(@user) %>
		<%= render 'unfollow' %>
	<% else %>
		<%= render 'follow' %>
	<% end %>
	</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
	<%= f.submit "アンフォロー", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  	| <%= link_to '削除', user, method: :delete, data: { confirm: "削除してもよろしいですか？"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'ユーザ更新') %>
<h1>プロフィールの更新</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "ユーザ更新", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank">更新</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザ一覧') %>
<h1>ユーザ一覧</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'MPosterアカウントを作成する') %>
<div class="row">
  <div class="span6 offset1 login-wrapper">

  	<h1>MPosterをはじめましょう</h1>

    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "MPosterアカウントを作成する", class: "btn btn-large btn-warning", style: "color: black;" %>
    <% end %>
		<p>ログインの場合、<%= link_to "こちら", signin_path %>へ</p>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
		<section>
			<%= render 'shared/stats' %>
		</section>
	</aside>
	<div class="span8">
		<%= render 'follow_form' if signed_in? %>
		<% if @user.microposts.any? %>
			<h3><%= @user.name %> の投稿（<%= @user.microposts.count %>件）</h3>
			<ol class="microposts">
				<%= render @microposts %>
			</ol>
			<%= will_paginate @microposts %>
		<% end %>
	</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
	<aside class="span4">
		<section>
			<%= gravatar_for @user %>
			<h1><%= @user.name %></h1>
			<span><%= link_to "プロフィールを表示", @user %></span>
			<span><b>ポスト:</b> <%= @user.microposts.count %></span>
		</section>
		<section>
			<%= render 'shared/stats' %>
			<% if @users.any? %>
				<div class="user_avatars">
					<% @users.each do |user| %>
						<%= link_to gravatar_for(user, size: 30), user %>
					<% end %>
				</div>
			<% end %>
		</section>
	</aside>
	<div class="span8">
		<h3><%= @title %></h3>
		<% if @users.any? %>
			<ul class="users">
				<%= render @users %>
			</ul>
		<% end %>
	</div>
</div>